---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    name: nginx
    type: test
spec:
  containers:
    - name: demo1
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP 

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx1
  labels: 
    name: nginx
    type: dev
spec:
  containers:
    - name: demo
      image: nginx
      ports:
        - containerPort: 80 
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx2
  labels: 
    name: nginx
    type: prod
spec:
  containers:
    - name: demo1
      image: nginx
      ports:
        - containerPort: 80 
          protocol: TCP