apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    name: nginx
    type: test
spec:
  containers:
    - name: demo1
      image: nginx
      ports:
        - containerPort: 80
          protocol: 80    